correct ci terraform gcp

diff --git a/.github/workflows/terraform-gcp.yml b/.github/workflows/terraform-gcp.yml
--- a/.github/workflows/terraform-gcp.yml
+++ b/.github/workflows/terraform-gcp.yml
@@ -16,6 +16,7 @@ permissions:
 jobs:
   terraform_env:
     runs-on: ubuntu-latest
+    environment: ${{ github.event.inputs.environment }}
 
     env:
       TF_IN_AUTOMATION: "true"
@@ -27,8 +28,9 @@ jobs:
 
       TFSTATE_BUCKET: "tfstate-bootstrap-project-487710"
       TF_VAR_ci_service_account_email: ${{ secrets.GCP_TERRAFORM_SA }}
-      TF_VAR_snowflake_account:   ${{ secrets.SNOWFLAKE_ACCOUNT }}
-      TF_VAR_snowflake_user:      ${{ secrets.SNOWFLAKE_USER }}
+
+      TF_VAR_snowflake_account:   ${{ secrets.SNOWFLAKE_ACCOUNT_NAME }}
+      TF_VAR_snowflake_user:      ${{ secrets.SNOWFLAKE_USERNAME }}
       TF_VAR_snowflake_password:  ${{ secrets.SNOWFLAKE_PASSWORD }}
       TF_VAR_snowflake_role:      ${{ secrets.SNOWFLAKE_ROLE }}
       TF_VAR_snowflake_warehouse: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
@@ -54,6 +56,16 @@ jobs:
           ENV="${{ github.event.inputs.environment }}"
           echo "dir=terraform/gcp/env/$ENV" >> $GITHUB_OUTPUT
           echo "prefix=gcp/env/$ENV" >> $GITHUB_OUTPUT
+
+      - name: Debug TF vars presence
+        run: |
+          [ -n "${TF_VAR_snowflake_account}" ] && echo "account OK" || echo "account MISSING"
+          [ -n "${TF_VAR_snowflake_user}" ] && echo "user OK" || echo "user MISSING"
+          [ -n "${TF_VAR_snowflake_password}" ] && echo "password OK" || echo "password MISSING"
+          [ -n "${TF_VAR_snowflake_role}" ] && echo "role OK" || echo "role MISSING"
+          [ -n "${TF_VAR_snowflake_warehouse}" ] && echo "warehouse OK" || echo "warehouse MISSING"
+          [ -n "${TF_VAR_snowflake_database}" ] && echo "database OK" || echo "database MISSING"
+          [ -n "${TF_VAR_snowflake_schema}" ] && echo "schema OK" || echo "schema MISSING"
 
       - name: Terraform init
         run: |
